name: instruqt-track-test
on: 
  workflow_dispatch:
  # push:
  #   paths:
  #     - 'tracks/*'
  #   branches:
  #     - devel

jobs:
  instruqt-track-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ansible
        run: sudo apt-get install ansible
      # - name: run playbook
      #   run: ansible-playbook /home/runner/work/ansible-meeting-bgs/ansible-meeting-bgs/.github/workflows/ansible/build-readme.yml
